-- YouTube Transcript RAG foundation schema.
-- This file is intentionally safe to rerun on the same schema.

create extension if not exists vector with schema extensions;

create table if not exists public.videos (
  id bigint generated by default as identity primary key,
  youtube_id text not null,
  title text,
  status text not null default 'pending',
  error_message text,
  ingestion_token uuid,
  ingestion_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint videos_youtube_id_key unique (youtube_id),
  constraint videos_youtube_id_format_check
    check (youtube_id ~ '^[A-Za-z0-9_-]{11}$'),
  constraint videos_status_check
    check (status in ('pending', 'ready', 'failed')),
  constraint videos_error_state_check
    check (
      (status = 'failed' and error_message is not null)
      or (status <> 'failed' and error_message is null)
    ),
  constraint videos_ingestion_state_check
    check (
      (
        status = 'pending'
        and ingestion_token is not null
        and ingestion_started_at is not null
      )
      or (
        status in ('ready', 'failed')
        and ingestion_token is null
        and ingestion_started_at is null
      )
    )
);

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null,
  embedding extensions.vector(384) not null,
  created_at timestamptz not null default now(),
  constraint documents_content_check check (btrim(content) <> ''),
  constraint documents_metadata_object_check
    check (jsonb_typeof(metadata) = 'object'),
  constraint documents_video_id_metadata_check
    check (
      metadata ? 'video_id'
      and (metadata ->> 'video_id') ~ '^[1-9][0-9]*$'
    ),
  constraint documents_ingestion_metadata_check
    check (
      metadata ?& array[
        'youtube_id',
        'start',
        'ingestion_token',
        'chunk_index'
      ]
      and (metadata ->> 'youtube_id') ~ '^[A-Za-z0-9_-]{11}$'
      and jsonb_typeof(metadata -> 'start') = 'number'
      and (metadata ->> 'start')::numeric >= 0
      and (metadata ->> 'ingestion_token')
        ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
      and jsonb_typeof(metadata -> 'chunk_index') = 'number'
      and (metadata ->> 'chunk_index') ~ '^[0-9]+$'
    )
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  role text not null,
  content text not null,
  created_at timestamptz not null default now(),
  constraint chat_messages_role_check
    check (role in ('user', 'assistant')),
  constraint chat_messages_content_check check (btrim(content) <> '')
);

create index if not exists documents_metadata_gin_idx
  on public.documents using gin (metadata);

create index if not exists documents_video_id_idx
  on public.documents (((metadata ->> 'video_id')::bigint));

create unique index if not exists documents_ingestion_chunk_idx
  on public.documents (
    (metadata ->> 'ingestion_token'),
    ((metadata ->> 'chunk_index')::integer)
  );

create index if not exists chat_messages_user_video_created_idx
  on public.chat_messages (user_id, video_id, created_at, id);

create index if not exists chat_messages_video_id_idx
  on public.chat_messages (video_id);

create or replace function public.match_documents(
  query_embedding extensions.vector(384),
  match_video_id bigint,
  match_count integer default 4
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity double precision
)
language sql
stable
security invoker
set search_path = ''
as $function$
  select
    document.id,
    document.content,
    document.metadata,
    1 - (
      document.embedding
      operator(extensions.<=>)
      query_embedding
    ) as similarity
  from public.documents as document
  where (document.metadata ->> 'video_id')::bigint = match_video_id
  order by
    document.embedding
    operator(extensions.<=>)
    query_embedding
  limit least(greatest(coalesce(match_count, 4), 1), 50);
$function$;

create or replace function public.claim_video_ingestion(
  requested_youtube_id text,
  stale_after_seconds integer default 900
)
returns table (
  id bigint,
  youtube_id text,
  title text,
  status text,
  error_message text,
  created_at timestamptz,
  updated_at timestamptz,
  ingestion_token uuid,
  acquired boolean
)
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  attempt_token uuid := extensions.gen_random_uuid();
  claimed public.videos%rowtype;
  lease_seconds integer := least(
    greatest(coalesce(stale_after_seconds, 900), 60),
    3600
  );
begin
  insert into public.videos as existing (
    youtube_id,
    status,
    error_message,
    ingestion_token,
    ingestion_started_at,
    updated_at
  )
  values (
    requested_youtube_id,
    'pending',
    null,
    attempt_token,
    now(),
    now()
  )
  on conflict on constraint videos_youtube_id_key do update
  set
    status = 'pending',
    error_message = null,
    ingestion_token = attempt_token,
    ingestion_started_at = now(),
    updated_at = now()
  where
    existing.status = 'failed'
    or (
      existing.status = 'pending'
      and existing.ingestion_started_at
        < now() - lease_seconds * interval '1 second'
    )
  returning existing.* into claimed;

  if found then
    delete from public.documents as document
    where (document.metadata ->> 'video_id')::bigint = claimed.id
      and document.metadata ->> 'ingestion_token' <> attempt_token::text;

    return query
    select
      claimed.id,
      claimed.youtube_id,
      claimed.title,
      claimed.status,
      claimed.error_message,
      claimed.created_at,
      claimed.updated_at,
      claimed.ingestion_token,
      true;
    return;
  end if;

  select video.*
  into strict claimed
  from public.videos as video
  where video.youtube_id = requested_youtube_id;

  return query
  select
    claimed.id,
    claimed.youtube_id,
    claimed.title,
    claimed.status,
    claimed.error_message,
    claimed.created_at,
    claimed.updated_at,
    claimed.ingestion_token,
    false;
end;
$function$;

create or replace function public.finalize_video_ingestion(
  target_video_id bigint,
  target_ingestion_token uuid
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  current_token uuid;
begin
  select video.ingestion_token
  into current_token
  from public.videos as video
  where video.id = target_video_id
  for update;

  if current_token is distinct from target_ingestion_token then
    delete from public.documents as document
    where (document.metadata ->> 'video_id')::bigint = target_video_id
      and document.metadata ->> 'ingestion_token'
        = target_ingestion_token::text;
    return false;
  end if;

  delete from public.documents as document
  where (document.metadata ->> 'video_id')::bigint = target_video_id
    and document.metadata ->> 'ingestion_token'
      <> target_ingestion_token::text;

  update public.videos
  set
    status = 'ready',
    error_message = null,
    ingestion_token = null,
    ingestion_started_at = null,
    updated_at = now()
  where videos.id = target_video_id;

  return true;
end;
$function$;

create or replace function public.fail_video_ingestion(
  target_video_id bigint,
  target_ingestion_token uuid,
  safe_error_message text
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  changed_rows integer;
begin
  delete from public.documents as document
  where (document.metadata ->> 'video_id')::bigint = target_video_id
    and document.metadata ->> 'ingestion_token'
      = target_ingestion_token::text;

  update public.videos
  set
    status = 'failed',
    error_message = left(
      coalesce(nullif(btrim(safe_error_message), ''), 'Video ingestion failed.'),
      500
    ),
    ingestion_token = null,
    ingestion_started_at = null,
    updated_at = now()
  where videos.id = target_video_id
    and videos.ingestion_token = target_ingestion_token;

  get diagnostics changed_rows = row_count;
  return changed_rows = 1;
end;
$function$;

alter table public.videos enable row level security;
alter table public.documents enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "Authenticated users can read videos" on public.videos;
create policy "Authenticated users can read videos"
  on public.videos
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can read documents" on public.documents;
create policy "Authenticated users can read documents"
  on public.documents
  for select
  to authenticated
  using (true);

drop policy if exists "Users can read their own chat messages"
  on public.chat_messages;
create policy "Users can read their own chat messages"
  on public.chat_messages
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can insert their own chat messages"
  on public.chat_messages;
create policy "Users can insert their own chat messages"
  on public.chat_messages
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

revoke all on table public.videos from anon, authenticated;
revoke all on table public.documents from anon, authenticated;
revoke all on table public.chat_messages from anon, authenticated;

grant select on table public.videos to authenticated;
grant select on table public.documents to authenticated;
grant select, insert on table public.chat_messages to authenticated;
grant usage, select on sequence public.chat_messages_id_seq to authenticated;

revoke execute on function public.match_documents(
  extensions.vector,
  bigint,
  integer
) from public, anon;
grant execute on function public.match_documents(
  extensions.vector,
  bigint,
  integer
) to authenticated, service_role;

revoke execute on function public.claim_video_ingestion(
  text,
  integer
) from public, anon, authenticated;
grant execute on function public.claim_video_ingestion(
  text,
  integer
) to service_role;

revoke execute on function public.finalize_video_ingestion(
  bigint,
  uuid
) from public, anon, authenticated;
grant execute on function public.finalize_video_ingestion(
  bigint,
  uuid
) to service_role;

revoke execute on function public.fail_video_ingestion(
  bigint,
  uuid,
  text
) from public, anon, authenticated;
grant execute on function public.fail_video_ingestion(
  bigint,
  uuid,
  text
) to service_role;

-- Per-user video libraries. Transcript vectors remain shared so ingesting the
-- same YouTube video stays idempotent, while membership and chat are private.
create table if not exists public.user_videos (
  user_id uuid not null references auth.users(id) on delete cascade,
  video_id bigint not null references public.videos(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_interacted_at timestamptz not null default now(),
  primary key (user_id, video_id)
);

create index if not exists user_videos_video_id_idx
  on public.user_videos (video_id);

create index if not exists user_videos_user_activity_idx
  on public.user_videos (user_id, last_interacted_at desc, video_id);

create index if not exists user_videos_last_interacted_idx
  on public.user_videos (last_interacted_at);

-- Preserve existing ownership inferred from chat history.
insert into public.user_videos (
  user_id,
  video_id,
  created_at,
  last_interacted_at
)
select
  message.user_id,
  message.video_id,
  least(min(message.created_at), min(video.created_at)),
  greatest(max(message.created_at), max(video.updated_at))
from public.chat_messages as message
join public.videos as video on video.id = message.video_id
group by message.user_id, message.video_id
on conflict (user_id, video_id) do update
set last_interacted_at = greatest(
  public.user_videos.last_interacted_at,
  excluded.last_interacted_at
);

-- On a single-user installation, retain videos that predate user libraries
-- even if that user has not chatted with them yet.
insert into public.user_videos (
  user_id,
  video_id,
  created_at,
  last_interacted_at
)
select
  sole_user.id,
  video.id,
  video.created_at,
  greatest(video.created_at, video.updated_at)
from public.videos as video
cross join lateral (
  select auth_user.id
  from auth.users as auth_user
  order by auth_user.created_at
  limit 1
) as sole_user
where (select count(*) from auth.users) = 1
  and not exists (
    select 1
    from public.user_videos as membership
    where membership.video_id = video.id
  )
on conflict (user_id, video_id) do nothing;

do $block$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'chat_messages_user_video_fkey'
      and conrelid = 'public.chat_messages'::regclass
  ) then
    alter table public.chat_messages
      add constraint chat_messages_user_video_fkey
      foreign key (user_id, video_id)
      references public.user_videos (user_id, video_id)
      on delete cascade;
  end if;
end;
$block$;

create or replace function public.add_user_video(
  target_user_id uuid,
  target_video_id bigint
)
returns table (
  library_created_at timestamptz,
  library_last_interacted_at timestamptz
)
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
begin
  perform 1
  from public.videos as video
  where video.id = target_video_id
  for update;

  if not found then
    raise exception 'Video not found'
      using errcode = 'foreign_key_violation';
  end if;

  insert into public.user_videos as membership (
    user_id,
    video_id
  )
  values (
    target_user_id,
    target_video_id
  )
  on conflict (user_id, video_id) do update
  set last_interacted_at = now();

  return query
  select
    membership.created_at,
    membership.last_interacted_at
  from public.user_videos as membership
  where membership.user_id = target_user_id
    and membership.video_id = target_video_id;
end;
$function$;

create or replace function public.list_user_videos(
  target_user_id uuid
)
returns table (
  id bigint,
  youtube_id text,
  title text,
  status text,
  error_message text,
  created_at timestamptz,
  updated_at timestamptz,
  library_created_at timestamptz,
  library_last_interacted_at timestamptz
)
language sql
stable
security invoker
set search_path = ''
as $function$
  select
    video.id,
    video.youtube_id,
    video.title,
    video.status,
    video.error_message,
    video.created_at,
    video.updated_at,
    membership.created_at,
    membership.last_interacted_at
  from public.user_videos as membership
  join public.videos as video on video.id = membership.video_id
  where membership.user_id = target_user_id
  order by membership.last_interacted_at desc, video.id desc;
$function$;

create or replace function public.touch_my_video(
  target_video_id bigint
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  changed_rows integer;
begin
  update public.user_videos as membership
  set last_interacted_at = now()
  where membership.user_id = (select auth.uid())
    and membership.video_id = target_video_id;

  get diagnostics changed_rows = row_count;
  return changed_rows = 1;
end;
$function$;

create or replace function public.remove_user_video(
  target_user_id uuid,
  target_video_id bigint
)
returns boolean
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  changed_rows integer;
  video_status text;
begin
  select video.status
  into video_status
  from public.videos as video
  where video.id = target_video_id
  for update;

  if not found then
    return false;
  end if;

  delete from public.user_videos as membership
  where membership.user_id = target_user_id
    and membership.video_id = target_video_id;

  get diagnostics changed_rows = row_count;
  if changed_rows = 0 then
    return false;
  end if;

  if video_status <> 'pending'
    and not exists (
      select 1
      from public.user_videos as membership
      where membership.video_id = target_video_id
    )
  then
    delete from public.documents as document
    where (document.metadata ->> 'video_id')::bigint = target_video_id;

    delete from public.videos as video
    where video.id = target_video_id;
  end if;

  return true;
end;
$function$;

create schema if not exists private;

create or replace function private.cleanup_inactive_user_videos(
  retention interval default interval '7 days'
)
returns table (
  memberships_deleted bigint,
  videos_deleted bigint
)
language plpgsql
volatile
security invoker
set search_path = ''
as $function$
declare
  removed_memberships bigint;
  removed_videos bigint;
begin
  if retention < interval '1 day' then
    raise exception 'Retention must be at least one day';
  end if;

  -- Use the same video-then-membership lock order as add/remove operations.
  -- This prevents cleanup from racing a user who is adding the same video.
  perform 1
  from public.videos as video
  where not exists (
    select 1
    from public.user_videos as membership
    where membership.video_id = video.id
      and membership.last_interacted_at >= now() - retention
  )
    and (
      video.status <> 'pending'
      or video.ingestion_started_at < now() - interval '1 day'
    )
  order by video.id
  for update;

  delete from public.user_videos as membership
  where membership.last_interacted_at < now() - retention;
  get diagnostics removed_memberships = row_count;

  delete from public.documents as document
  where exists (
    select 1
    from public.videos as video
    where video.id = (document.metadata ->> 'video_id')::bigint
      and not exists (
        select 1
        from public.user_videos as membership
        where membership.video_id = video.id
      )
      and (
        video.status <> 'pending'
        or video.ingestion_started_at < now() - interval '1 day'
      )
  );

  delete from public.videos as video
  where not exists (
    select 1
    from public.user_videos as membership
    where membership.video_id = video.id
  )
    and (
      video.status <> 'pending'
      or video.ingestion_started_at < now() - interval '1 day'
    );
  get diagnostics removed_videos = row_count;

  return query select removed_memberships, removed_videos;
end;
$function$;

alter table public.user_videos enable row level security;

drop policy if exists "Users can read their own video memberships"
  on public.user_videos;
create policy "Users can read their own video memberships"
  on public.user_videos
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Users can add their own video memberships"
  on public.user_videos;
create policy "Users can add their own video memberships"
  on public.user_videos
  for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can update their own video memberships"
  on public.user_videos;
create policy "Users can update their own video memberships"
  on public.user_videos
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

drop policy if exists "Users can delete their own video memberships"
  on public.user_videos;
create policy "Users can delete their own video memberships"
  on public.user_videos
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "Authenticated users can read videos" on public.videos;
create policy "Users can read videos in their library"
  on public.videos
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.user_videos as membership
      where membership.user_id = (select auth.uid())
        and membership.video_id = videos.id
    )
  );

drop policy if exists "Authenticated users can read documents"
  on public.documents;
create policy "Users can read documents for videos in their library"
  on public.documents
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.user_videos as membership
      where membership.user_id = (select auth.uid())
        and membership.video_id =
          (documents.metadata ->> 'video_id')::bigint
    )
  );

revoke all on table public.user_videos from anon, authenticated;
grant select, insert, update, delete
  on table public.user_videos to authenticated;

revoke execute on function public.add_user_video(
  uuid,
  bigint
) from public, anon, authenticated;
grant execute on function public.add_user_video(
  uuid,
  bigint
) to service_role;

revoke execute on function public.list_user_videos(
  uuid
) from public, anon, authenticated;
grant execute on function public.list_user_videos(
  uuid
) to service_role;

revoke execute on function public.touch_my_video(
  bigint
) from public, anon;
grant execute on function public.touch_my_video(
  bigint
) to authenticated;

revoke execute on function public.remove_user_video(
  uuid,
  bigint
) from public, anon, authenticated;
grant execute on function public.remove_user_video(
  uuid,
  bigint
) to service_role;

revoke all on schema private from public, anon, authenticated, service_role;
revoke execute on function private.cleanup_inactive_user_videos(
  interval
) from public, anon, authenticated, service_role;

create extension if not exists pg_cron;

do $block$
declare
  existing_job_id bigint;
begin
  select jobid
  into existing_job_id
  from cron.job
  where jobname = 'cleanup-inactive-user-videos';

  if existing_job_id is not null then
    perform cron.unschedule(existing_job_id);
  end if;

  perform cron.schedule(
    'cleanup-inactive-user-videos',
    '17 3 * * *',
    $command$select * from private.cleanup_inactive_user_videos(interval '7 days')$command$
  );
end;
$block$;
